### ISSUE TITLE
Really poor documentation

### ISSUE THREAD

**Issue by brando130** [beiller/Gen3Rig#1]
Docs for this tool are really bad. 

"Select the armature and click "Convert Genesis 3 rig" in properties panel" - For me this was not in the Properties panel, but in the 3D View's Tools panel, which on my screen I needed to find the little "+" icon at the top right of the 3D view and drag it over to even see that menu. Before finally finding this I dug and dug through the Properties panel looking for it, per the documentation.

It's "at bottom but top of physpose tools" - So that's the bottom, or the top? Or the top of the bottom? 

I saw on a comment board about using the Genesis 3 template, "Generate Physpose Rig", all that, but none of that appears in the Gen 3 part of the instructions in the readme.

**Comment by beiller** [comment]
Hi Brando,

I thought the tools panel is on the left hand side (toggle by pressing 't')

To see this panel, press 'n' to toggle the right hand side panel, and scroll to the bottom usually...?

I will update the readme.

**Comment by beiller** [comment]
Also sadly, the things you complained about are the standard for blender plugins. I find they tend to show up in random places sometimes. I hope you were able to get something working. The newest version is for blender 2.79+ and uses the default rigify rig now.
